apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cl01-outpost-mob-matrixx-prd-01 #set cluster name
  region: us-east-1
  version: "1.24"

vpc:
  id: "vpc-0bf73d966b7a6f180" #vpc id
  subnets:
    private:
      us-east-1c:
      #outpost:
          id: "subnet-05a938b3672e52088"  
nodeGroups:
############### EKS NODE4 Checkpoint-Engine ##############################
  - name: eks-outpost-checkpoint-eng-cl01-lappng004
    instanceType: m5.8xlarge
    instanceName: eks-outpost-checkpoint-eng-cl01-ng004-aws.mob.matrixx.prd-01
    labels:
      role: checkpoint-engine
      appName: checkpoint-engine
    desiredCapacity: 1
    maxSize: 2
    minSize: 1
    placement:
      groupName: "eks-op-checkpoint-eng"
    ssh:
      allow: true
      enableSsm: true
      publicKeyName: outpost-aws.mob.matrixx.prod-01-instance-key
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: 'a69158ca-7d05-464e-98f5-0353b84e3452'
    subnets:
      - "subnet-05a938b3672e52088" 
        #- "outpost"
    preBootstrapCommands:
      - sudo yum -y install nfs-utils
      - sudo mkdir -p /shared-logging-storage
      - sudo mkdir -p /shared-coredump-storage
      - sudo mkdir -p /shared-storage
      - sudo mkdir -p /fast-shared-storage
      - sudo systemctl start nfs-server.service
      - sudo systemctl enable nfs-server.service
      - sudo echo "10.100.201.68:/shared-logging-storage      /shared-logging-storage  nfs4     rw,nosuid,defaults      0       0"  >> /etc/fstab
      - sudo echo "10.100.201.68:/shared-coredump-storage      /shared-coredump-storage nfs4     rw,nosuid,defaults      0       0"  >> /etc/fstab
      - sudo echo "10.100.200.152:/shared-storage      /shared-storage  nfs4     rw,nosuid,defaults      0       0"  >> /etc/fstab
      - sudo echo "10.100.201.249:/fast-shared-storage      /fast-shared-storage  nfs4     rw,nosuid,defaults      0       0"  >> /etc/fstab
      - sudo mount -a
      - sudo chown -R 1000:1000 /shared-logging-storage
      - sudo chown -R 1000:1000 /shared-coredump-storage
      - sudo chown -R 1000:1000 /shared-storage
      - sudo chown -R 1000:1000 /fast-shared-storage
      - sudo echo "net.ipv4.tcp_rmem = 4096    16777216    33554432" >> /etc/sysctl.conf
      - sudo echo "net.ipv4.tcp_wmem = 4096    16777216    33554432" >> /etc/sysctl.conf
      - sudo echo "net.core.wmem_default = 16777216" >> /etc/sysctl.conf
      - sudo echo "net.core.wmem_max = 33554432" >> /etc/sysctl.conf
      - sudo echo "net.core.rmem_default = 16777216" >> /etc/sysctl.conf
      - sudo echo "net.core.rmem_max = 33554432" >> /etc/sysctl.conf
      - sudo sysctl -p
    privateNetworking: true
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
